from .loader import NODE_CLASS_MAPPINGS as LOADER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as LOADER_NAMES
from .keyer import NODE_CLASS_MAPPINGS as KEYER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as KEYER_NAMES
from .utils import NODE_CLASS_MAPPINGS as UTILS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as UTILS_NAMES

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(LOADER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(KEYER_MAPPINGS)
NODE_CLASS_MAPPINGS.update(UTILS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS.update(LOADER_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(KEYER_NAMES)
NODE_DISPLAY_NAME_MAPPINGS.update(UTILS_NAMES)
